let name, name2, name3, name4, name5;
let old, old2, old3, old4, old5;
let i=1;
name= prompt(`P${i}: What is your name`);
old= prompt("How old are you ");
i++;
name2= prompt(`P${i}: What is your name`);
old2= prompt("How old are you ");
i++;
name3= prompt(`P${i}: What is your name`);
old3= prompt("How old are you ");
i++;
name4= prompt(`P${i}: What is your name`);
old4= prompt("How old are you ");
i++;
name5= prompt(`P${i}: What is your name`);
old5= prompt("How old are you ");
i++;
console.log(`${name} is ${old} years old`);
console.log(`${name2} is ${old2} years old`);
console.log(`${name3} is ${old3} years old`);
console.log(`${name4} is ${old4} years old`);
console.log(`${name5} is ${old5} years old`);